### ISSUE TITLE
Bug in latest Parquet-dotnet reading date_string in alltypes_dicitonary.plain.parquet

### ISSUE THREAD

**Issue by AndyCross** [elastacloud/parquet-dotnet#138]
C:\src\parquet-dotnet\src\parq\bin\Debug\netcoreapp1.1>dotnet parq.dll interactive InputFilePath=C:\src\parquet-dotnet\src\Parquet.Test\data\alltypes_dictionary.plain.parquet
Input file chosen as C:\src\parquet-dotnet\src\Parquet.Test\data\alltypes_dictionary.plain.parquet

Unhandled Exception: Parquet.ParquetException: fatal error reading column 'date_string_col' ---> System.ArgumentException: The value "System.Byte[]" is not of type "System.String" and cannot be used in this generic collection.
Parameter name: value
   at System.ThrowHelper.ThrowWrongValueTypeArgumentException(Object value, Type targetType)
   at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
   at Parquet.File.Values.PlainValuesReader.ReadByteArray(Byte[] data, SchemaElement schemaElement, IList destination) in C:\src\parquet-dotnet\src\Parquet\File\Values\PlainValuesReader.cs:line 235
   at Parquet.File.Values.PlainValuesReader.Read(BinaryReader reader, SchemaElement schema, IList destination, Int64 maxValues) in C:\src\parquet-dotnet\src\Parquet\File\Values\PlainValuesReader.cs:line 52
   at Parquet.File.PColumn.ReadDictionaryPage(PageHeader ph) in C:\src\parquet-dotnet\src\Parquet\File\PColumn.cs:line 133
   at Parquet.File.PColumn.Read(String columnName) in C:\src\parquet-dotnet\src\Parquet\File\PColumn.cs:line 59
   at Parquet.ParquetReader.Read() in C:\src\parquet-dotnet\src\Parquet\ParquetReader.cs:line 114
   --- End of inner exception stack trace ---
   at Parquet.ParquetReader.Read() in C:\src\parquet-dotnet\src\Parquet\ParquetReader.cs:line 119
   at Parquet.ParquetReader.ReadFile(String fullPath, ParquetOptions options) in C:\src\parquet-dotnet\src\Parquet\ParquetReader.cs:line 73
   at parq.Program.ReadFromParquetFile(String path, Int64& fileLen) in C:\src\parquet-dotnet\src\parq\Program.cs:line 79
   at parq.Program.Main(String[] args) in C:\src\parquet-dotnet\src\parq\Program.cs:line 37

**Comment by aloneguid** [comment]
@AndyCross it's a bug indeed, fixed now (see PR). One thing to note here - `alltypes_dicitonary.plain.parquet` specifically encodes strings as byte arrays (doesn't have proper annotations). You can force parquet.net to read them out as strings by passing `ParquetOptions` object to the reader and setting `TreatByteArrayAsString = true;`.

**Comment by dimpalbhole** [comment]
@aloneguid I am still facing this issue.
Error is {"fatal error reading column 'SN'"} and message is fatal error reading column 'SN'.
I have set TreatByteArrayAsString = true .

**Comment by aloneguid** [comment]
@dimpalbhole can you raise an issue with all details include so we can have a look?
